# -*- coding: utf-8 -*-
"""variante.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tw1Q2OKZtj0cWts1J4AMKzWf_eGAzGOG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ruta = '/content/ok INFROME SEF. BOL.2222.xlsx'
datos_completos = pd.read_excel(ruta, header=None)

print("ARCHIVO ORIGINAL")
print(datos_completos.head(12))

def limpiar_datos(datos):

    # BALANCE
    balance = datos.iloc[1:5, 1:5].copy()
    balance.columns = ['Anio', 'Activos', 'Pasivos', 'Patrimonio']
    balance = balance.iloc[1:].reset_index(drop=True)

    # RESULTADOS
    resultados = datos.iloc[6:10, 1:5].copy()
    resultados.columns = ['Anio', 'Ingresos', 'Gastos', 'Utilidad']
    resultados = resultados.iloc[1:].reset_index(drop=True)

    # Convertir a número
    for col in balance.columns:
        balance[col] = pd.to_numeric(balance[col], errors='coerce')

    for col in resultados.columns:
        resultados[col] = pd.to_numeric(resultados[col], errors='coerce')

    return balance, resultados

balance, resultados = limpiar_datos(datos_completos)

print("\n=== BALANCE ===")
print(balance)

print("\n=== RESULTADOS ===")
print(resultados)

class Empresa:

    def __init__(self, balance, resultados):
        self.balance = balance
        self.resultados = resultados
        self.datos = {}

    def construir_diccionario(self):
        for i in range(len(self.balance)):
            año = int(self.balance['Anio'][i])

            self.datos[año] = {
                'activos': self.balance['Activos'][i],
                'pasivos': self.balance['Pasivos'][i],
                'patrimonio': self.balance['Patrimonio'][i],
                'ingresos': self.resultados['Ingresos'][i],
                'gastos': self.resultados['Gastos'][i],
                'utilidad': self.resultados['Utilidad'][i]
            }

        return self.datos

def calcular_metricas(datos):
    metricas = {}

    for año, info in datos.items():
        a = info['activos']
        p = info['pasivos']
        k = info['patrimonio']

        solvencia = round((k / a) * 100, 2) if a != 0 else 0
        endeudamiento = round(p / k, 2) if k != 0 else 0

        metricas[año] = {
            'solvencia': solvencia,
            'endeudamiento': endeudamiento
        }

    return metricas

empresa = Empresa(balance, resultados)

datos = empresa.construir_diccionario()

print("\n=== DICCIONARIO ===")
for año, info in datos.items():
    print(año, info)

metricas = calcular_metricas(datos)

print("\n=== METRICAS ===")
for año, m in metricas.items():
    print(año, m)

df = pd.DataFrame.from_dict(datos, orient='index')
df.index.name = 'Año'
df = df.reset_index()

df['Solvencia (%)'] = (df['patrimonio'] / df['activos']) * 100
df['Endeudamiento'] = df['pasivos'] / df['patrimonio']

df = df.round(2)

print("\n=== DATAFRAME FINAL ===")
print(df)

años_buenos = [año for año in df['Año'] if df[df['Año']==año]['Solvencia (%)'].values[0] > 15]

print("\nAños con buena solvencia:", años_buenos)

plt.figure(figsize=(8,5))
plt.plot(df['Año'], df['activos'], marker='o', label='Activos')
plt.plot(df['Año'], df['pasivos'], marker='s', label='Pasivos')

plt.title("Evolución Financiera")
plt.xlabel("Año")
plt.ylabel("Valor")
plt.legend()
plt.grid()

plt.show()

from sklearn.tree import DecisionTreeClassifier, plot_tree #prediccion para desempeño futuro

df_ml = df.copy()
df_ml['solvencia']     = (df_ml['patrimonio'] / df_ml['activos']) * 100
df_ml['endeudamiento'] = df_ml['pasivos'] / df_ml['patrimonio']
df_ml['margen']        = df_ml['utilidad'] / df_ml['ingresos']          #CALCULAMOS INDICADORES DE DF YA EXISTENTES

df_ml['desempeno'] = ((df_ml['solvencia'] > 15) & (df_ml['utilidad'] > 0)).astype(int)         #1= BUENO 0=MALO SI SOLVENCIA < 15% y utilidad POSITIVA

FEATURES = ['solvencia', 'endeudamiento', 'margen']
arbol = DecisionTreeClassifier(max_depth=2, random_state=42)
arbol.fit(df_ml[FEATURES], df_ml['desempeno'])                                   #ENTRENAR LOS DATOS CON LOS DATOS QUE LE DIMOS QUE SON LOS DE LOS 3 AÑOS ANTERIORES

solvencia_2026     = 14.0    # %
endeudamiento_2026 = 5.5     # veces
margen_2026        = -0.02   # negativo = pérdida

futuro = pd.DataFrame([{
    'solvencia': solvencia_2026,
    'endeudamiento': endeudamiento_2026,
    'margen': margen_2026
}])

resultado = arbol.predict(futuro)[0]
print(f"\n=== PREDICCIÓN 2026 ===")
print(f"  Solvencia proyectada  : {solvencia_2026}%")
print(f"  Endeudamiento         : {endeudamiento_2026}x")
print(f"  Margen de utilidad    : {margen_2026:.0%}")
print(f"  → Desempeño esperado  : {'BUENO ✓' if resultado == 1 else 'EN RIESGO ✗'}")

plt.figure(figsize=(10, 4))
plot_tree(arbol, feature_names=FEATURES, class_names=['En Riesgo', 'Bueno'],
          filled=True, rounded=True, fontsize=10)
plt.title("Árbol de Decisión — Predicción de desempeñO futuro")
plt.tight_layout()
plt.show()